#:schema ./node_modules/wrangler/config-schema.json
name = "teeny-notes-e2e"
account_id = "tb-SAaZ-KxUTY-yhh8UpMJZJw"
main = "./worker.ts"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 8787

[observability]
enabled = true

[vars]
RESPOND_WITH_ERRORS = "true"

[[d1_databases]]
binding = "PRIMARY_DB"
database_name = "teeny-notes-e2e-db-v2"
database_id = "976f398e0d37-teeny-notes-e2e-db-v2"
preview_database_id = "TEENY_AUTO_CREATE"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PRIMARY_R2"
bucket_name = "e7273839cf64-teenybase-51d607a7fb43"
preview_bucket_name = "teeny-notes-preview"
